//Types of design patterns
//디자인 패턴의 3가지 유형
//1. Structural design pattern(구조 디자인 패턴) : 객체가 어떻게 구성되고 결합되어 더 큰 구조를 형성하는 지 설명.
//  ex. MVC(Model-View-Controller), MVVM (Model-View-ViewModel), Facade ...
//2. Behavioral design pattern(행동 디자인 패턴) : 객체가 서로 통신하는 방법을 설명.
//  ex. Delegation, Strategy, Observer ...
//3. Creational design pattern(생성 디자인 패턴) : 객체를 생성하거나 인스턴스화하는 방법 설명.
//  ex. Builder, Singleton, Prototype ...
