
platform :ios, '11.0'

target 'PhotoTagger' do
  inhibit_all_warnings!
  use_frameworks!

  # Pods for PhotoTagger
  pod 'Alamofire', '~> 4.7.0'
  pod 'SwiftyJSON', '~> 4.0.0'
  
end

post_install do |pi|
    pi.pods_project.targets.each do |t|
      t.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
      end
    end
end
